services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unwired-server
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - .:/app
    networks:
      - unwired-net

  db:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - unwired-net

volumes:
  postgres-data:


networks:
  unwired-net:
