version: '3.8'
services:
  devcontainer:
    container_name: unwired-server
    image: mcr.microsoft.com/devcontainers/python:3.12
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - unwired-net

  db:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - unwired-net
  
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:8.8
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lanops.net
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    depends_on:
      - db
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - unwired-net

volumes:
  postgres-data:
  pgadmin:

networks:
  unwired-net: